In [10]:
import geopandas as gpd 
import geodatasets

In [11]:
gpd.__version__

'1.1.3'

In [12]:
gpd.datasets.available

[]

In [13]:
from geodatasets import get_path
nybb = gpd.read_file(get_path('nybb'))

Downloading file 'nybb_16a.zip' from 'https://www.nyc.gov/assets/planning/download/zip/data-maps/open-data/nybb_16a.zip' to 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache'.
Extracting 'nybb_16a/nybb.shp' from 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip' to 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip.unzip'
Extracting 'nybb_16a/nybb.shx' from 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip' to 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip.unzip'
Extracting 'nybb_16a/nybb.dbf' from 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip' to 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip.unzip'
Extracting 'nybb_16a/nybb.prj' from 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip' to 'C:\Users\muzic\AppData\Local\geodatasets\geodatasets\Cache\nybb_16a.zip.unzip'

In [14]:
print(type(nybb))

<class 'geopandas.geodataframe.GeoDataFrame'>

In [15]:
nybb

,BoroCode,BoroName,Shape_Leng,Shape_Area,geometry
0,5,Staten Island,330470.010332,1.623820e+09,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
1,4,Queens,896344.047763,3.045213e+09,"MULTIPOLYGON (((1029606.077 156073.814, 102957..."
2,3,Brooklyn,741080.523166,1.937479e+09,"MULTIPOLYGON (((1021176.479 151374.797, 102100..."
3,1,Manhattan,359299.096471,6.364715e+08,"MULTIPOLYGON (((981219.056 188655.316, 980940...."
4,2,Bronx,464392.991824,1.186925e+09,"MULTIPOLYGON (((1012821.806 229228.265, 101278..."

In [16]:
nybb.head()

,BoroCode,BoroName,Shape_Leng,Shape_Area,geometry
0,5,Staten Island,330470.010332,1.623820e+09,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
1,4,Queens,896344.047763,3.045213e+09,"MULTIPOLYGON (((1029606.077 156073.814, 102957..."
2,3,Brooklyn,741080.523166,1.937479e+09,"MULTIPOLYGON (((1021176.479 151374.797, 102100..."
3,1,Manhattan,359299.096471,6.364715e+08,"MULTIPOLYGON (((981219.056 188655.316, 980940...."
4,2,Bronx,464392.991824,1.186925e+09,"MULTIPOLYGON (((1012821.806 229228.265, 101278..."

In [17]:
nybb.describe()

       BoroCode     Shape_Leng    Shape_Area
count  5.000000       5.000000  5.000000e+00
mean   3.000000  558317.333911  1.685981e+09
std    1.581139  249002.452978  9.034868e+08
min    1.000000  330470.010332  6.364715e+08
25%    2.000000  359299.096471  1.186925e+09
50%    3.000000  464392.991824  1.623820e+09
75%    4.000000  741080.523166  1.937479e+09
max    5.000000  896344.047763  3.045213e+09

In [18]:
nybb.keys()

Index(['BoroCode', 'BoroName', 'Shape_Leng', 'Shape_Area', 'geometry'], dtype='object')

Basic Geometry

In [20]:
import shapely 
shapely.__version__

'2.1.2'

In [21]:
from shapely.geometry import Point, LineString, Polygon, MultiPolygon